version: '3.8'

services:
  backend:
    # image: eastwesser/car-rental-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/images:/app/images
    environment:
      - PORT=8080

  frontend:
    # image: eastwesser/car-rental-frontend
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend